name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup config file
      run: |
        echo "IP=${SAP_IP}" >> gosap.env
        echo "PORT=${SAP_PORT}" >> gosap.env
        echo "COMPANY_DB=${SAP_COMPANY_DB}" >> gosap.env
        echo "DB_PASSWORD=${SAP_USERNAME_DB}" >> gosap.env
        echo "DB_USERNAME=${SAP_PASSWORD_DB}" >> gosap.env
        cat gosap.env

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v --cover ./...
