name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup config file
      run: |
        export SAP_IP=${{secrets.SAP_IP}}
        export SAP_PORT=${{secrets.SAP_PORT}}
        export SAP_COMPANY_DB=${{secrets.COMPANY_DB}}
        export SAP_USERNAME_DB=${{secrets.SAP_USERNAME_DB}}
        export SAP_PASSWORD_DB=${{secrets.SAP_PASSWORD_DB}}
        echo "IP=${SAP_IP}" >> gosap.env
        echo "PORT=${SAP_PORT}" >> gosap.env
        echo "COMPANY_DB=${SAP_COMPANY_DB}" >> gosap.env
        echo "DB_PASSWORD=${SAP_USERNAME_DB}" >> gosap.env
        echo "DB_USERNAME=${SAP_PASSWORD_DB}" >> gosap.env
        cat gosap.env

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v --cover ./...
